id: P001817
initial_creation_type: ocr
source_metadata:
  id: bdr:W20170
  title: ལྕགས་སྟག་ཞིབ་གཞུང
  author: ''
  volumes:
    df05479b16af4114b4129d1218c6b715:
      image_group_id: I5506
      title: ''
      volume_number: 1
      total_pages: 522
      base_file: v001.txt
