id: P001817
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:23:18.355917
source_metadata:
  id: bdr:W20170
  title: ལྕགས་སྟག་ཞིབ་གཞུང
  author: ''
  volumes:
    df05479b16af4114b4129d1218c6b715:
      image_group_id: I5506
      title: ''
      volume_number: 1
      total_pages: 522
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
